name: clip_tag
description: 4PDA website rules aggregator
publish_to: "none"
version: 4.0.1+8

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.12.2
  device_apps: ^2.2.0
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_bbcode: ^1.4.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/app_icon.png
